[package]
name = "mindy-html"
version = "0.1.0"
authors = ["Jérôme Garcia <jerome.garcia@bashroom.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.0", features = ["web"] }
mindy-engine = { path = "../mindy-engine" }
palette = "0.7.6"
log = "0.4.27"
base64 = "0.22.1"


[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
