[application]

[web.app]
# HTML title tag content
title = "syb-mindmap"


[web.watcher]
reload_html = true
watch_path = [ "assets/main.css" ]

# include `assets` in web platform
[web.resource]
style = []
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
icon = ["assets/logo/logo_256.png"]