[tasks.html_assets_import]
script_runner = "bash"
cwd = "mindy-html"
script = "cp --recursive --force ../assets/logo/ assets/"
args = ["build", "--platform", "web"]
category = "Build"

[tasks.html_build]
script_runner = "bash"
cwd = "mindy-html"
command = "dx"
args = ["build", "--platform", "web"]
category = "Build"
dependencies = [
    "html_assets_import"
]

[tasks.html_serve]
script_runner = "bash"
cwd = "mindy-html"
command = "dx"
args = ["serve"]
category = "Run"
dependencies = [
    "html_assets_import"
]