extend = [
    { path = "idea-plugin/Makefile.tasks.toml" },
    { path = "mindy-html/Makefile.tasks.toml" },
    { path = "vscode-extension/syb-mindmap/Makefile.tasks.toml" },
]
[tasks.setup]
script = [
    "cargo install cargo-make --version 0.37.24 || true",
    "cargo install cargo-edit --version 0.13.2 || true",
]

[tasks.release]
script_runner = "bash"
command = 'bash/repository/release/index.bash'
category = "Release"

[tasks.deploy_main]
script_runner = "bash"
script = '''
#!/bin/bash
set -e

most_recent_tag="$( git describe --tags --abbrev=0 )"
git checkout main
git reset --hard "${most_recent_tag}"
git push --force-with-lease
'''
category = "Release"
