extend = [
    { path = "idea-plugin/Makefile.tasks.toml" },
    { path = "mindy-html/Makefile.tasks.toml" },
    { path = "vscode-extension/syb-mindmap/Makefile.tasks.toml" },
]
[tasks.setup]
script = [
    "cargo install cargo-make --version 0.37.24 || true",
    "cargo install cargo-edit --version 0.13.2 || true",
]

[tasks.release]
script_runner = "bash"
script = '''
#!/bin/bash
set -e
git cliff --bump --config .cliff.toml > .github/CHANGELOG.md
git cliff --unreleased --bump --config .cliff.toml > vscode-extension/syb-mindmap/CHANGELOG.md
git add .github/CHANGELOG.md

version="$(git cliff --config .cliff.toml --bumped-version 2> /dev/null)"

(
    cd vscode-extension/syb-mindmap
    yarn version --no-git-tag-version --no-commit-hooks --non-interactive --new-version "${version}"
    git add package.json
)

(
    cd idea-plugin
    sed --in-place "s#version.set.*#version.set(\"${version}\")#" build.gradle.kts
    git add build.gradle.kts
)
cargo set-version --workspace "${version}" --offline

git add --all
git commit --message "chore: release tag '${version}'"

git tag "${version}"
git push --follow-tags
'''
category = "Release"

[tasks.deploy_main]
script_runner = "bash"
script = '''
#!/bin/bash
set -e

most_recent_tag="$( git describe --tags --abbrev=0 )"
git checkout main
git reset --hard "${most_recent_tag}"
git push --force-with-lease
'''
category = "Release"
