[tasks.setup]
script = [
    "cargo install cargo-make --version 0.37.24 || true",
    "cargo install cargo-edit --version 0.13.2 || true",
]

[tasks.html_build]
script_runner = "bash"
cwd = "mindy-html"
command = "dx"
args = ["build", "--platform", "web"]
category = "Build"

[tasks.html_serve]
script_runner = "bash"
cwd = "mindy-html"
command = "dx"
args = ["serve"]
category = "Run"

[tasks.vscode_build]
script_runner = "bash"
cwd = "vscode-extension/syb-mindmap"
script = '''
#!/bin/bash
set -e
rm -rf media/*
cp --recursive --force ../../target/dx/mindy-html/debug/web/public/* media
'''
category = "Build"
dependencies = ["html_build"]

[tasks.vscode_deploy]
script_runner = "bash"
cwd = "vscode-extension/syb-mindmap"
script = '''
#!/bin/bash
set -e
version="$( cat package.json | jq --raw-output --compact-output .version )"
code --uninstall-extension "syb-mindmap-${version}.vsix" || true
code --update-extensions && yarn run vsce package --allow-missing-repository
code --install-extension "syb-mindmap-${version}.vsix"
'''
category = "Deploy"
dependencies = ["vscode_build"]


[tasks.release]
script_runner = "bash"
script = '''
#!/bin/bash
set -e
git cliff --unreleased --bump > .github/CHANGELOG.md
git add .github/CHANGELOG.md

version="$(git cliff --bumped-version 2> /dev/null)"

(
    cd vscode-extension/syb-mindmap
    yarn version --no-git-tag-version --no-commit-hooks --non-interactive --new-version "${version}"
    git add package.json
)
cargo set-version --workspace "${version}" --offline

git add --all
git commit --message "chore: release tag '${version}'"

git tag "${version}"
git push --follow-tags
'''
category = "Release"

[tasks.deploy_main]
script_runner = "bash"
script = '''
#!/bin/bash
set -e

most_recent_tag="$( git describe --tags --abbrev=0 )"
git checkout main
git reset --hard "${most_recent_tag}"
git push --force-with-lease
'''
category = "Release"
