

[tasks.vscode_build]
script_runner = "bash"
cwd = "vscode-extension/syb-mindmap"
script = '''
#!/bin/bash
set -e
rm -rf media/*
cp --recursive --force ../../target/dx/mindy-html/debug/web/public/* media
'''
category = "Build"
dependencies = ["html_build"]

[tasks.vscode_deploy]
script_runner = "bash"
cwd = "vscode-extension/syb-mindmap"
script = '''
#!/bin/bash
set -e
version="$( cat package.json | jq --raw-output --compact-output .version )"
code --uninstall-extension "syb-mindmap-${version}.vsix" || true
code --update-extensions && yarn run vsce package --allow-missing-repository
code --install-extension "syb-mindmap-${version}.vsix"
'''
category = "Deploy"
dependencies = ["vscode_build"]

[tasks.vscode_publish]
script_runner = "bash"
cwd = "vscode-extension/syb-mindmap"
script = '''
#!/bin/bash
set -e
yarn run vsce publish
'''
category = "Publish"
dependencies = ["vscode_deploy"]