[package]
name = "mindy-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
palette = "0.7.6"
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"

[lib]
name = "mindy_engine"
path = "src/lib.rs"