[package]
name = "mindy-engine"
version = "0.3.2"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
tracing = "0.1.41"
serde_json = "1.0.140"
serde_yaml = "0.9.34+deprecated"

[lib]
name = "mindy_engine"
path = "src/lib.rs"
